// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8fz54s-v56DPWH5ycNfNHCvgPYa0WJCk',
    appId: '1:76319784599:web:090ceac707cf2850da33d2',
    messagingSenderId: '76319784599',
    projectId: 'flutterfleppy',
    authDomain: 'flutterfleppy.firebaseapp.com',
    storageBucket: 'flutterfleppy.firebasestorage.app',
    measurementId: 'G-3T0S6WKD2N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFwxefLpzVjcwtdKdo6wKV0YO-7Tukr6w',
    appId: '1:76319784599:android:95a97d31dea68d20da33d2',
    messagingSenderId: '76319784599',
    projectId: 'flutterfleppy',
    storageBucket: 'flutterfleppy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9B6FdOMv5qc1wXnKnDpW7muvEVxS2sag',
    appId: '1:76319784599:ios:313536baeaacd4adda33d2',
    messagingSenderId: '76319784599',
    projectId: 'flutterfleppy',
    storageBucket: 'flutterfleppy.firebasestorage.app',
    androidClientId: '76319784599-2njmk14igso2f4ou3dbt1u0dt56lai7s.apps.googleusercontent.com',
    iosBundleId: 'com.example.fixflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9B6FdOMv5qc1wXnKnDpW7muvEVxS2sag',
    appId: '1:76319784599:ios:313536baeaacd4adda33d2',
    messagingSenderId: '76319784599',
    projectId: 'flutterfleppy',
    storageBucket: 'flutterfleppy.firebasestorage.app',
    androidClientId: '76319784599-2njmk14igso2f4ou3dbt1u0dt56lai7s.apps.googleusercontent.com',
    iosBundleId: 'com.example.fixflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8fz54s-v56DPWH5ycNfNHCvgPYa0WJCk',
    appId: '1:76319784599:web:7514c2258890726cda33d2',
    messagingSenderId: '76319784599',
    projectId: 'flutterfleppy',
    authDomain: 'flutterfleppy.firebaseapp.com',
    storageBucket: 'flutterfleppy.firebasestorage.app',
    measurementId: 'G-ZJMF9Y02SC',
  );

}